# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pr: none

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      git config user.email "dcfinlinson@gmail.com"
      git config user.name "Derek Finlinson"
      git remote set-url origin https://$(github.user):$(github.pat)@github.com/derekfinlinson/d365-cli.git
    displayName: 'git config'
  - script: |
      npm install
    displayName: 'npm install'
  - script: |
      npm run check
    displayName: 'check change files'
  - script: |
      npm run build
    displayName: 'build'
  - script: |
      npm run test
    displayName: 'test'
  - script: |
      npm run beachball:publish -n $(npm.authtoken) -y
    displayName: 'beachball publish'